title: Allyson Park
email: parkallyson@gmail.com
description: >-
  Hi, I'm Allyson, a full stack developer at HP. I love to learn and I love to teach! I graduated from Berkeley in 2022 and have been living in San Diego since.
baseurl: ""
url: "https://allysonpark.github.io/"
github_username: allysonpark

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page layout forked from Jekyll Researcher theme by Ankit Sultana"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "Projects"
    link: "projects"
  - name: "Educational"
    link: "educational"
  - name: "Contact"
    link: "contact"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
